/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/decimated.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/decimated.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty001" position={[0, -0.078, 8]} rotation={[1.668, -0.112, -2.524]}>
          <group name="layer_1013" position={[0, 1.887, 0]}>
            <mesh name="petal009" geometry={nodes.petal009.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, -1.566, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal010" geometry={nodes.petal010.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[Math.PI, -0.787, Math.PI]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal011" geometry={nodes.petal011.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal012" geometry={nodes.petal012.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal013" geometry={nodes.petal013.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, 1.571, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal015" geometry={nodes.petal015.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, Math.PI / 4, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal016" geometry={nodes.petal016.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal017" geometry={nodes.petal017.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, -0.789, 0]} scale={[0.703, 0.677, 0.711]} />
          </group>
          <group name="layer_2013" position={[0, 0.615, 0]}>
            <mesh name="petal001" geometry={nodes.petal001.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, -0.789, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal002" geometry={nodes.petal002.geometry} material={materials['Material.002']} position={[0, -7.494, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal003" geometry={nodes.petal003.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, Math.PI / 4, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal004" geometry={nodes.petal004.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, 1.571, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal005" geometry={nodes.petal005.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal006" geometry={nodes.petal006.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal007" geometry={nodes.petal007.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[Math.PI, -0.787, Math.PI]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal008" geometry={nodes.petal008.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, -1.566, 0]} scale={[0.703, 0.677, 0.711]} />
          </group>
          <group name="Empty002" position={[-0.032, -7.035, 0.001]} rotation={[0, -Math.PI / 4, 0]} scale={1.186}>
            <mesh name="Circle_disc002" geometry={nodes.Circle_disc002.geometry} material={materials['Material.002']} position={[-0.286, 4.897, -5.837]} scale={3.082} />
          </group>
          <group name="Empty006" position={[0.039, -7.035, 0.07]} rotation={[Math.PI, -0.78, Math.PI]} scale={1.379}>
            <mesh name="Circle_disc006" geometry={nodes.Circle_disc006.geometry} material={materials['Material.002']} position={[-0.062, 4.211, -5.001]} scale={2.651} />
          </group>
          <group name="Empty007" position={[-0.032, -7.035, 0.001]} rotation={[0, -Math.PI / 2, 0]} scale={1.186}>
            <mesh name="Circle_disc001" geometry={nodes.Circle_disc001.geometry} material={materials['Material.002']} position={[-0.286, 4.897, -5.837]} scale={3.082} />
          </group>
          <group name="Empty008" position={[-0.032, -7.035, 0.001]} rotation={[0, Math.PI / 4, 0]} scale={1.186}>
            <mesh name="Circle_disc008" geometry={nodes.Circle_disc008.geometry} material={materials['Material.002']} position={[-0.286, 4.897, -5.837]} scale={3.082} />
          </group>
          <group name="Empty010" position={[-0.032, -7.035, 0.001]} scale={1.186}>
            <mesh name="Circle_disc009" geometry={nodes.Circle_disc009.geometry} material={materials['Material.002']} position={[-0.286, 4.897, -5.837]} scale={3.082} />
          </group>
          <mesh name="Circle_disc003" geometry={nodes.Circle_disc003.geometry} material={materials['Material.002']} position={[-6.811, -1.23, 0.478]} rotation={[0, Math.PI / 2, 0]} scale={3.654} />
          <mesh name="Circle_disc004" geometry={nodes.Circle_disc004.geometry} material={materials['Material.002']} position={[-4.599, -1.23, 4.582]} rotation={[-Math.PI, 0.778, -Math.PI]} scale={3.654} />
          <mesh name="Circle_disc005" geometry={nodes.Circle_disc005.geometry} material={materials['Material.002']} position={[0.243, -1.23, 6.961]} rotation={[Math.PI, -0.009, Math.PI]} scale={3.654} />
          <mesh name="Middle_circle_small013" geometry={nodes.Middle_circle_small013.geometry} material={materials['Material.002']} position={[0, 2.438, 0]} scale={[4.398, 3.013, 4.398]} />
        </group>
        <group name="Empty127" position={[0, -0.078, -8]} rotation={[1.655, 0.123, -0.702]}>
          <group name="layer_1014" position={[0, 1.887, 0]}>
            <mesh name="petal018" geometry={nodes.petal018.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, -0.789, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal030" geometry={nodes.petal030.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal038" geometry={nodes.petal038.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, Math.PI / 4, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal055" geometry={nodes.petal055.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, 1.571, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal072" geometry={nodes.petal072.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal089" geometry={nodes.petal089.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal115" geometry={nodes.petal115.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[Math.PI, -0.787, Math.PI]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal132" geometry={nodes.petal132.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, -1.566, 0]} scale={[0.703, 0.677, 0.711]} />
          </group>
          <group name="layer_2014" position={[0, 0.615, 0]}>
            <mesh name="petal140" geometry={nodes.petal140.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, -1.566, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal157" geometry={nodes.petal157.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[Math.PI, -0.787, Math.PI]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal174" geometry={nodes.petal174.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal200" geometry={nodes.petal200.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal208" geometry={nodes.petal208.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, 1.571, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal222" geometry={nodes.petal222.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, Math.PI / 4, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal223" geometry={nodes.petal223.geometry} material={materials['Material.002']} position={[0, -7.494, 0]} scale={[0.703, 0.677, 0.711]} />
            <mesh name="petal224" geometry={nodes.petal224.geometry} material={materials['Material.002']} position={[0, -7.466, 0]} rotation={[0, -0.789, 0]} scale={[0.703, 0.677, 0.711]} />
          </group>
          <group name="Empty011" position={[-0.032, -7.035, 0.001]} scale={1.186}>
            <mesh name="Circle_disc105" geometry={nodes.Circle_disc105.geometry} material={materials['Material.002']} position={[-0.286, 4.897, -5.837]} scale={3.082} />
          </group>
          <group name="Empty120" position={[-0.032, -7.035, 0.001]} rotation={[0, Math.PI / 4, 0]} scale={1.186}>
            <mesh name="Circle_disc106" geometry={nodes.Circle_disc106.geometry} material={materials['Material.002']} position={[-0.286, 4.897, -5.837]} scale={3.082} />
          </group>
          <group name="Empty121" position={[-0.032, -7.035, 0.001]} rotation={[0, -Math.PI / 2, 0]} scale={1.186}>
            <mesh name="Circle_disc112" geometry={nodes.Circle_disc112.geometry} material={materials['Material.002']} position={[-0.286, 4.897, -5.837]} scale={3.082} />
          </group>
          <group name="Empty122" position={[0.039, -7.035, 0.07]} rotation={[Math.PI, -0.78, Math.PI]} scale={1.379}>
            <mesh name="Circle_disc107" geometry={nodes.Circle_disc107.geometry} material={materials['Material.002']} position={[-0.062, 4.211, -5.001]} scale={2.651} />
          </group>
          <group name="Empty126" position={[-0.032, -7.035, 0.001]} rotation={[0, -Math.PI / 4, 0]} scale={1.186}>
            <mesh name="Circle_disc111" geometry={nodes.Circle_disc111.geometry} material={materials['Material.002']} position={[-0.286, 4.897, -5.837]} scale={3.082} />
          </group>
          <mesh name="Circle_disc108" geometry={nodes.Circle_disc108.geometry} material={materials['Material.002']} position={[0.243, -1.23, 6.961]} rotation={[Math.PI, -0.009, Math.PI]} scale={3.654} />
          <mesh name="Circle_disc109" geometry={nodes.Circle_disc109.geometry} material={materials['Material.002']} position={[-4.599, -1.23, 4.582]} rotation={[-Math.PI, 0.778, -Math.PI]} scale={3.654} />
          <mesh name="Circle_disc110" geometry={nodes.Circle_disc110.geometry} material={materials['Material.002']} position={[-6.811, -1.23, 0.478]} rotation={[0, Math.PI / 2, 0]} scale={3.654} />
          <mesh name="Middle_circle_small014" geometry={nodes.Middle_circle_small014.geometry} material={materials['Material.002']} position={[0, 2.438, 0]} scale={[4.398, 3.013, 4.398]} />
        </group>
        <spotLight intensity={1630542.392} angle={1.422} penumbra={1} decay={2} color="#6e00ff" position={[19.639, 0, -0.001]} rotation={[-0.359, 1.555, -0.835]} target={nodes.Point001.target}>
          <primitive object={nodes.Point001.target} position={[0, 0, -1]} />
        </spotLight>
        <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={85.256} position={[20.429, 0, 0]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={materials['Material.004']} position={[21.871, 0, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[4.884, 22, 6.645]} />
      </group>
    </group>
  )
}

useGLTF.preload('/decimated.glb')
